import 'SeedModules.PageBuilder/modules/components/builder/page';
import 'SeedModules.PageBuilder/modules/components/server/settings';
import 'SeedModules.PageBuilder/modules/components/builder/pageForm';
import 'SeedModules.PageBuilder/modules/components/builder/preview';
import 'SeedModules.PageBuilder/modules/components/toolbox/builderToolbox';
import 'SeedModules.PageBuilder/modules/components/datasource/list';
import 'SeedModules.PageBuilder/modules/components/datasource/form';
import 'SeedModules.PageBuilder/modules/components/datasource/baseinfo';
import 'SeedModules.PageBuilder/modules/controllers/pageCommon';
