export enum DefaultFormTypes {
  fieldset = 'fieldset',
  section = 'section',
  actions = 'actions',
  text = 'text',
  textarea = 'textarea',
  number = 'number',
  password = 'password',
  checkbox = 'checkbox',
  checkboxes = 'checkboxes',
  select = 'select',
  submit = 'submit',
  button = 'button',
  radios = 'radios',
  radiosInline = 'radios-inline',
  radiobuttons = 'radiobuttons',
  help = 'help',
  template = 'template',
  tab = 'tab',
  tabs = 'tabs',
  array = 'array',
  tabarray = 'tabarray',
  subforms = 'subforms'
}
